version: '3.8'
services:
  vpn:
    container_name: softether
    build: .
    volumes:
      - vpn_data:/svr
    ports:
      - '500:500/udp'
      - '4500:4500/udp'
      - '5555:5555/tcp'
    cap_add:
      - NET_ADMIN
volumes:
  vpn_data:
